blueprint:
  name: Smart Battery Management
  description: Comprehensive battery management system incorporating planning, control, and self-consumption
  domain: automation
  source_url: https://github.com/Mewongu/hass_blueprint_ferroamp_battery_optimization
  input:
    # Battery System Sensors
    battery_soc_sensor:
      name: Battery State of Charge Sensor
      description: Sensor measuring battery state of charge
      selector:
        entity:
          domain: sensor
    power_in_sensor:
      name: Power Input Sensor
      description: Sensor measuring power being drawn from the grid
      selector:
        entity:
          domain: sensor
    power_out_sensor:
      name: Power Output Sensor
      description: Sensor measuring power being exported to the grid
      selector:
        entity:
          domain: sensor

    # Battery Planner Sensors
    planner_action_sensor:
      name: Battery Planner Action Sensor
      description: Sensor indicating the current recommended action from the planner
      selector:
        entity:
          domain: sensor
    planner_power_sensor:
      name: Battery Planner Power Sensor
      description: Sensor indicating the recommended power level from the planner
      selector:
        entity:
          domain: sensor

    # Battery Planner Settings
    planner_update_interval:
      name: Planner Update Interval
      description: How often to update the battery plan (in minutes)
      default: "*"
      selector:
        select:
          options:
            - label: "Every minute"
              value: "*"
            - label: "Every 2 minutes"
              value: "/2"
            - label: "Every 5 minutes"
              value: "/5"
            - label: "Every 10 minutes"
              value: "/10"
            - label: "Every 15 minutes"
              value: "/15"
            - label: "Every 30 minutes"
              value: "/30"
            - label: "Every hour"
              value: "0"

    # Self-Consumption Settings
    power_threshold:
      name: Power Change Threshold
      description: Minimum power change threshold in watts before updating
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          step: 10
          unit_of_measurement: W

    # Helper Entities
    last_discharge_helper:
      name: Last Discharge Helper
      description: Input number entity to store last discharge power
      selector:
        entity:
          domain: input_number

variables:
  battery_soc: !input battery_soc_sensor
  power_in: !input power_in_sensor
  power_out: !input power_out_sensor
  planner_action: !input planner_action_sensor
  planner_power: !input planner_power_sensor
  update_interval: !input planner_update_interval
  power_threshold: !input power_threshold
  last_discharge: !input last_discharge_helper

trigger:
  # Trigger 1: Regular planning update
  - platform: time_pattern
    minutes: !input planner_update_interval

  # Trigger 2: Monitor planner recommendations
  - platform: state
    entity_id:
      - !input planner_action_sensor
      - !input planner_power_sensor

  # Trigger 3: Monitor power changes for self-consumption
  - platform: state
    entity_id: !input power_in_sensor
    for:
      seconds: 1
  - platform: state
    entity_id: !input power_out_sensor
    for:
      seconds: 1

action:
  - variables:
      trigger_id: "{{ trigger.platform }}"
      current_action: "{{ states(planner_action) }}"
      recommended_power: "{{ states(planner_power) | float(0) }}"

  - choose:
      # Handle planning updates
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'time_pattern' }}"
        sequence:
          - response_variable: plan
            service: stenite_battery_planner.plan
            data:
              battery_soc: "{{ states(battery_soc) | float }}"

      # Handle battery control based on planner recommendations
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'state' and 
                 (trigger.entity_id in [planner_action, planner_power]) }}
        sequence:
          - choose:
              # Charging action
              - conditions:
                  - condition: template
                    value_template: "{{ current_action == 'charge' }}"
                sequence:
                  - service: ferroamp.charge
                    data:
                      power: "{{ recommended_power | abs }}"

              # Discharging action
              - conditions:
                  - condition: template
                    value_template: "{{ current_action == 'discharge' }}"
                sequence:
                  - service: ferroamp.discharge
                    data:
                      power: "{{ recommended_power }}"

              # Idle action
              - conditions:
                  - condition: template
                    value_template: "{{ current_action == 'idle' }}"
                sequence:
                  - service: ferroamp.discharge
                    data:
                      power: 0

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'state' and 
                 trigger.entity_id in [power_in, power_out] and
                 current_action == 'self_consumption' }}
        sequence:
          - variables:
              power_in_value: "{{ states(power_in) | float(0) }}"
              power_out_value: "{{ states(power_out) | float(0) }}"
              last_discharge_value: "{{ states(last_discharge) | float(0) }}"
              current_power_flow: "{{ (power_in_value - power_out_value) * 1000 }}"
              true_consumption: "{{ current_power_flow + last_discharge_value }}"
              new_power: >
                {% if (true_consumption - last_discharge_value) | abs > power_threshold %}
                  {{ true_consumption | round(0) }}
                {% else %}
                  {{ last_discharge_value | round(0) }}
                {% endif %}
          # Determine whether to charge or discharge based on consumption value
          - service: >
              {% if true_consumption < 0 %}
                ferroamp.charge
              {% else %}
                ferroamp.discharge
              {% endif %}
            data:
              power: "{{ new_power | abs }}"
          # Store the consumption value for next iteration
          - service: input_number.set_value
            target:
              entity_id: !input last_discharge_helper
            data:
              value: "{{ new_power }}"

mode: parallel